// Generated by scripts/build-react-gradient-engine.mjs. Do not edit.
// Incoming FeralUI React bundle for Ghost light (Aurora type)
export const GHOST_LIGHT_META = {
  name: "Ghost light",
  type: "aurora",
  speed: 14,
  noise: 8,
};
